apps/accounts/urls.py
from django.urls import path

from apps.accounts.views import LoginView, RegisterView, LogoutView

app_name="accounts"
urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("register", RegisterView.as_view(), name="register"),
    path("logout", LogoutView.as_view(), name="logout"),
]

apps/store/urls.py
from django.urls import path

from apps.store.views import HomeView, ExploreView, AuthorDetailView, ProductDetailView, ProductCreateView, \
    ProductUpdateView

app_name = "store"
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('explore/', ExploreView.as_view(), name="explore"),
    path('create/', ProductCreateView.as_view(), name="create"),
    path('author/<str:username>', AuthorDetailView.as_view(), name="author_detail"),
    path('products/<int:pk>', ProductDetailView.as_view(), name="product_detail"),
    path('products/<int:pk>/update', ProductUpdateView.as_view(), name="product_update"),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config.settings import STATIC_ROOT, STATIC_URL, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.store.urls')),
    path('accounts/', include('apps.accounts.urls')),
]

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

liberty_makret/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

apps/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    avatar = models.FileField(upload_to="users/avatar/%Y/%m/%d")

apps/shared/models.py
from django.db import models


class AbstractModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

apps/store/models.py
from django.db import models
from django.urls import reverse

from apps.accounts.models import User
from apps.shared.models import AbstractModel


class Category(AbstractModel):
    name = models.CharField(max_length=32)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Product(AbstractModel):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=255)
    author = models.ForeignKey(User, models.CASCADE, "products")
    owner_full_name = models.CharField(max_length=56)
    owner_username = models.CharField(max_length=56)
    category = models.ForeignKey(Category, models.CASCADE, "products")
    price = models.DecimalField(max_digits=7, decimal_places=2)
    price_in_dollar = models.DecimalField(max_digits=10, decimal_places=2)
    end_date = models.DateTimeField()
    photo = models.FileField(upload_to="products/photo/%Y/%m/%d", default="default/discover-04.jpg")

    def __str__(self):
        return "{0} by {1}".format(self.name, self.author)

    def get_absolute_url(self):
        return reverse("store:product_detail", kwargs={"pk": self.pk})

apps/accounts/forms.py
from django import forms

from apps.accounts.models import User


class RegisterForm(forms.ModelForm):
    avatar = forms.FileField()

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "password", "avatar")


class LoginForm(forms.Form):
    username = forms.CharField(max_length=56)
    password = forms.CharField(max_length=56)

apps/store/forms.py
from django import forms

from apps.store.models import Product


class ProductForm(forms.ModelForm):
    photo = forms.FileField()

    class Meta:
        model = Product
        fields = ('name', 'description', 'author', 'category', 'owner_full_name', 'owner_username', 'end_date', 'price',
                  'price_in_dollar', 'photo')

apps/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views import View

from apps.accounts.forms import RegisterForm, LoginForm


class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'accounts/register.html', {"form": form})

    def post(self, request):
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect("store:home")
        else:
            return render(request, 'accounts/register.html', {"form": form})


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, "accounts/login.html", {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('store:home')
        return render(request, 'accounts/login.html', {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('store:home')

apps/shared/views.py
from django.shortcuts import render

# Create your views here.

apps/store/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, DetailView, CreateView, UpdateView

from apps.accounts.models import User
from apps.store.forms import ProductForm
from apps.store.models import Product, Category


class HomeView(View):
    def get(self, request):
        products = Product.objects.order_by("-created_at")[:8]
        return render(request, 'store/index.html', {"products": products})


class ExploreView(View):
    def get(self, request):
        categories = Category.objects.all()
        top_products = [Product.objects.filter(category=i).order_by('-created_at').first() for i in categories]
        products = Product.objects.order_by("-created_at")[:8]
        return render(request, 'store/explore.html', {"products": products, "top_products": top_products})


class AuthorDetailView(LoginRequiredMixin, View):
    def get(self, request, username):
        user = User.objects.get(username=username)
        products = Product.objects.filter(author=user)
        return render(request, 'store/author.html', context={"author": user, "products": products})


class ProductDetailView(View):
    def get(self, request, pk):
        product = Product.objects.get(pk=pk)
        return render(request, 'store/details.html', {"product": product})


class ProductCreateView(CreateView):
    template_name = 'store/create.html'
    form_class = ProductForm
    model = Product
    # fields = ('name', 'description', 'author', 'category', 'owner_full_name', 'owner_username', 'end_date', 'price',
              # 'price_in_dollar', 'photo')
    success_url = reverse_lazy("store:home")


class ProductUpdateView(UpdateView):
    template_name = 'store/create.html'
    form_class = ProductForm
    model = Product
    # fields = ('name', 'description', 'author', 'category', 'owner_full_name', 'owner_username', 'end_date', 'price',
              # 'price_in_dollar', 'photo')
    success_url = reverse_lazy("store:home")

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}    
    
    <div class="container my-5 py-5">
    <h2 class="mt-5"  style="color: #000;">Login</h2>
    <p  style="color: #000;">Don't have an account. <a href="{% url 'accounts:register' %}">Register</a></p>
    <hr>
        <form method="post">
            {% csrf_token %}
            {{ form.as_div }}
            <input type="submit" value="Login" class="btn btn-outline-primary">
        </form>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <style>
    h1, h2, label, p, input{
        color: #000 !important;
    }
    </style>

    <div class="container my-5 py-5">
    <h2  style="color: #000;" class="mt-5">Register</h2>
    <p  style="color: #000;">Already have an account. <a href="{% url 'accounts:login' %}">Login</a></p>
    <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save" class="btn btn-outline-primary">
        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet">

    <title>Liberty NFT</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-liberty-market.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <!--

    TemplateMo 577 Liberty Market

    https://templatemo.com/tm-577-liberty-market

    -->
</head>

<body>

<!-- ***** Preloader Start ***** -->
<div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
        <span class="dot"></span>
        <div class="dots">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
</div>
<!-- ***** Preloader End ***** -->

<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="index.html" class="logo">
                        <img src="{% static 'images/logo.png' %}" alt="">
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li><a href="{% url 'store:home' %}">Home</a></li>
                        <li><a href="{% url 'store:explore' %}">Explore</a></li>

                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'store:author_detail' user.username %}">Author</a></li>
                            <li><a href="{% url 'store:create' %}">Create Yours</a></li>
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        {% endif %}

                    </ul>
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ***** Header Area End ***** -->


{% block body %}

{% endblock %}


<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright © 2022 <a href="#">Liberty</a> NFT Marketplace Co., Ltd. All rights reserved.
                    &nbsp;&nbsp;
                    Designed by <a title="HTML CSS Templates" rel="sponsored" href="https://templatemo.com"
                                   target="_blank">TemplateMo</a></p>
            </div>
        </div>
    </div>
</footer>


<!-- Scripts -->
<!-- Bootstrap core JavaScript -->
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/isotope.min.js' %}"></script>
<script src="{% static 'js/owl-carousel.js' %}"></script>

<script src="{% static 'js/tabs.js' %}"></script>
<script src="{% static 'js/popup.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

</body>
</html>

templates/store/author.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

    <div class="page-heading normal-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h6>Author Details</h6>
                    <h2>View Details For Author</h2>
                    <div class="buttons">
                        <div class="main-button">
                            <a href="{% url 'store:explore' %}">Explore Our Items</a>
                        </div>
                        <div class="border-button">
                            <a href="create.html">Create Your NFT</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="author-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="author">
                        <img src="{{ author.avatar.url }}" alt="" style="border-radius: 50%; max-width: 170px;">
                        <h4>{{ author.first_name }} {{ author.last_name }}<br> <a href="#">@{{ author.username }}</a>
                        </h4>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="right-info">
                        <div class="row">
                            <div class="col-4">
                                <div class="info-item">
                                    <i class="fa fa-heart"></i>
                                    <h6>1238 <em>Likes</em></h6>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="info-item">
                                    <i class="fa fa-hand"></i>
                                    <h6>1238 <em>Likes</em></h6>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="info-item">
                                    <i class="fa fa-dollar"></i>
                                    <h6>1238 <em>Likes</em></h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="section-heading">
                        <div class="line-dec"></div>
                        <h2>{{ author.first_name }} {{ author.last_name }}'s <em>Items</em>.</h2>
                    </div>
                </div>
                {% for product in products %}
                    <div class="col-lg-3 col-md-6">
                        <div class="item">
                            <div class="row">
                                <div class="col-lg-12">
                <span class="author">
                  <img src="{{ author.avatar.url }}" alt="" style="max-width: 50px; border-radius: 50%;">
                </span>
                                    <img src="{{ product.photo.url }}" alt="" style="border-radius: 20px;">
                                    <h4>{{ product.name }}</h4>
                                </div>
                                <div class="col-lg-12">
                                    <div class="line-dec"></div>
                                    <div class="row">
                                        <div class="col-6">
                                            <span>Current Bid: <br> <strong>{{ product.price }} ETH</strong></span>
                                        </div>
                                        <div class="col-6">
                                            <span>Ends In: <br> <strong>{{ product.end_date|date:"F d" }}</strong></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="main-button">
                                        <a href="details.html">View Details</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="create-nft">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="section-heading">
                        <div class="line-dec"></div>
                        <h2>Create Your NFT & Put It On The Market.</h2>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="main-button">
                        <a href="create.html">Create Your NFT Now</a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="item first-item">
                        <div class="number">
                            <h6>1</h6>
                        </div>
                        <div class="icon">
                            <img src="assets/images/icon-02.png" alt="">
                        </div>
                        <h4>Set Up Your Wallet</h4>
                        <p>Lorem ipsum dolor sit amet, consectetu dipiscingei elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="item second-item">
                        <div class="number">
                            <h6>2</h6>
                        </div>
                        <div class="icon">
                            <img src="assets/images/icon-04.png" alt="">
                        </div>
                        <h4>Add Your Digital NFT</h4>
                        <p>Lorem ipsum dolor sit amet, consectetu dipiscingei elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="item">
                        <div class="icon">
                            <img src="assets/images/icon-06.png" alt="">
                        </div>
                        <h4>Sell Your NFT &amp; Make Profit</h4>
                        <p>Lorem ipsum dolor sit amet, consectetu dipiscingei elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/store/create.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    <style>
        input{
            width: 500px !important;
        }
    </style>

    <div class="page-heading normal-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h6>Liberty NFT Market</h6>
                    <h2>Create Your NFT Now.</h2>
                    <div class="buttons">
                        <div class="main-button">
                            <a href="{% url 'store:explore' %}">Explore Our Items</a>
                        </div>
                        <div class="border-button">
                            <a href="create.html">Create Your NFT</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="item-details-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">
                        <div class="line-dec"></div>
                        <h2>Apply For <em>Your Item</em> Here.</h2>
                    </div>
                </div>
                <div class="col-lg-12">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Save" class="btn btn-primary">
                    </form>
                </div>
                
            </div>
        </div>
    </div>

{% endblock %}

templates/store/details.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    <div class="page-heading normal-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h6>Liberty NFT Market</h6>
                    <h2>View Item Details</h2>
                    <div class="buttons">
                        <div class="main-button">
                            <a href="{% url 'store:explore' %}">Explore Our Items</a>
                        </div>
                        <div class="border-button">
                            <a href="{% url 'store:create' %}">Create Your NFT</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="item-details-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">
                        <div class="line-dec"></div>
                        <h2>View Details <em>For Item</em> Here.</h2>
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="left-image">
                        <img src="{{ product.photo.url }}" alt="" style="border-radius: 20px;">
                    </div>
                </div>
                <div class="col-lg-5 align-self-center">
                    <h4>{{ product.name }}</h4>
                    <span class="author">
            <img src="{{ product.author.avatar.url }}" alt="" style="max-width: 50px; border-radius: 50%;">
            <h6>{{ product.author.first_name }}{{ product.author.last_name }}<br><a
                    href="#">@{{ product.author.username }}</a></h6>
          </span>
                    <p>{{ product.description }}</p>
                    <div class="row">
                        <div class="col-3">
              <span class="bid">
                Current Bid<br><strong>{{ product.price }} ETH</strong><br><em>(${{ product.price_in_dollar }})</em>
              </span>
                        </div>
                        <div class="col-4">
              <span class="owner">
                Owner<br><strong>{{ product.owner_full_name }}</strong><br><em>(@{{ product.owner_username }})</em>
              </span>
                        </div>
                        <div class="col-5">
              <span class="ends">
                Ends In<br><strong>{{ product.end_date|date:"d-m-Y" }}</strong><br>
              </span>
                            {% if request.user == product.author %}
                                <a href="{% url 'store:product_update' product.id %}" class="btn btn-primary">Update</a>
                            {% endif %}
                        </div>
                    </div>
                    <form action="submit">
                        <label for="quantity-text">Place Bid:</label>
                        <input placeholder="1 ETH" class="quantity-text">
                        <button type="submit" id="form-submit" class="main-button">Submit Now</button>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <div class="create-nft">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="section-heading">
                        <div class="line-dec"></div>
                        <h2>Create Your NFT & Put It On The Market.</h2>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="main-button">
                        <a href="{% url 'store:create' %}">Create Your NFT Now</a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="item first-item">
                        <div class="number">
                            <h6>1</h6>
                        </div>
                        <div class="icon">
                            <img src="assets/images/icon-02.png" alt="">
                        </div>
                        <h4>Set Up Your Wallet</h4>
                        <p>There are 5 different HTML pages included in this NFT <a href="https://templatemo.com/page/1"
                                                                                    target="_blank" rel="nofollow">website
                            template</a>. You can edit or modify any section on any page as you required.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="item second-item">
                        <div class="number">
                            <h6>2</h6>
                        </div>
                        <div class="icon">
                            <img src="assets/images/icon-04.png" alt="">
                        </div>
                        <h4>Add Your Digital NFT</h4>
                        <p>If you would like to support our TemplateMo website, please visit <a rel="nofollow"
                                                                                                href="https://templatemo.com/contact"
                                                                                                target="_parent">our
                            contact page</a> to make a PayPal contribution. Thank you.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="item">
                        <div class="icon">
                            <img src="assets/images/icon-06.png" alt="">
                        </div>
                        <h4>Sell Your NFT &amp; Make Profit</h4>
                        <p>NFT means Non-Fungible Token that are used in digital cryptocurrency markets. There are many
                            different kinds of NFTs in the industry.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}